import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Providers } from "./provider";


export const metadata: Metadata = {
  title: "food shere community",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
      >
        <Providers>
          <Navbar />
          <main>
            {children}
          </main>
          <Footer />
        </Providers>

      </body>
    </html>
  );
}
